fix: improve log support
casbin/gorm-adapter pull request #105
Opened 2021-04-28 09:11 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #104

2021-04-28 09:12 UTC, closetool commented
@hsluoyz @arafat-java plz review

2021-04-28 10:18 UTC, hsluoyz requested changes

2021-04-28 10:18 UTC, hsluoyz commented on adapter.go
> +
no new line

2021-04-29 16:06 UTC, hsluoyz approved these changes

2021-04-29 16:06 UTC, merged

2021-04-30 02:43 UTC, closetool commented
@arafat-java fixed

2021-04-30 04:49 UTC, hsluoyz commented
@closetool why there's no GitHub Actions bot? I want this: https://github.com/casbin/casbin/pull/773#issuecomment-826350808

![image](https://user-images.githubusercontent.com/3787410/116649683-70ff8980-a9b2-11eb-98a7-4f669a206076.png)