feat: Re-support sqlite
casbin/gorm-adapter pull request #128
Opened 2021-09-03 13:23 UTC by lwnmengjing

2021-09-04 04:46 UTC, tangyang9464 commented
@lwnmengjing plz fix it
![image](https://user-images.githubusercontent.com/45587763/132082728-fe41f349-404c-4bc6-af95-5a825934c172.png)

see Details
![image](https://user-images.githubusercontent.com/45587763/132082730-31179ad9-4d4e-49ba-9ac0-1f4cddeee64d.png)

2021-09-04 05:01 UTC, tangyang9464 requested changes

2021-09-04 05:52 UTC, hsluoyz commented
@lwnmengjing we will not merge this into master, maybe in a new sqlite branch

2021-09-05 13:49 UTC, lwnmengjing commented on opens_sqlite3.go
> +	"sqlserver": sqlserver.Open,
This allows you to use go build tag to avoid dependency on GCC

2021-09-05 14:49 UTC, closed without merging