fix: support customized table
casbin/gorm-adapter pull request #168
Opened 2022-06-19 15:18 UTC by JalinWang

fix #167

2022-06-19 17:17 UTC, hsluoyz commented
@basimsahaf @tangyang9464 plz review

2022-06-20 00:48 UTC, tangyang9464 requested changes

2022-06-20 00:48 UTC, tangyang9464 commented on adapter.go
> +
Don't have to use reflect to check here, it's poor performance, and the loss is not worth it

2022-06-20 00:48 UTC, tangyang9464 commented on adapter.go
> +		customTable: db.Statement.Context.Value(customTableKey{}),
Instead of using Context to pass customTable, you can use a.customTable directly

2022-06-20 00:48 UTC, tangyang9464 commented on adapter.go
> +func (a *Adapter) newTableInstance() *CasbinRule {
Why not use getTableInstance

2022-06-20 00:48 UTC, tangyang9464 commented on adapter.go
> +	line := a.newTableInstance()
should use getTableInstance

2022-06-20 00:48 UTC, tangyang9464 commented on adapter.go
> +	line := a.newTableInstance()
should use getTableInstance

2022-06-22 21:13 UTC, basimsahaf commented on adapter.go
> +	line := a.newTableInstance()
this will return a `CasbinRule` table and not the custom one

2022-06-22 21:15 UTC, basimsahaf commented on adapter.go
> +	for _, field := range []string{"ID", "Ptype", "V0", "V1", "V2", "V3", "V4", "V5", "V6", "V7"} {
why are we forcing the column names to be one from this list? If it's a custom table, can we not let users define their own column names?

2022-06-22 21:16 UTC, basimsahaf commented on adapter.go
> +	for _, field := range []string{"ID", "Ptype", "V0", "V1", "V2", "V3", "V4", "V5", "V6", "V7"} {
For GORM autodelete to work, the name of the column has to be `deletedat`. Which means the custom table will not support GORM autodelete

2022-06-26 12:40 UTC, tangyang9464 requested changes

2022-06-26 12:40 UTC, tangyang9464 commented on adapter.go
> +	modelType := reflect.TypeOf(a.getTableObject())
if modelType is CasbinRule, we can query directly without having to go through the next steps

2022-06-26 12:40 UTC, tangyang9464 commented on adapter.go
> +	modelType := reflect.TypeOf(t)
think about if modelType is CasbinRule

2022-06-26 12:40 UTC, tangyang9464 commented on adapter.go
> +	cusLines := reflect.ValueOf(lines)
if modelType is CasbinRule, just ``lines = lines.([]CasbinRule)``

2022-06-26 12:40 UTC, tangyang9464 commented on adapter.go
> +		if err := a.dbCreate(tx, &newP[i]); err != nil {
Please check if these two methods should be placed outside the ``for`` loop and executed only once rather than repeating.

2022-06-26 12:40 UTC, tangyang9464 commented on adapter_test.go
> +	a.AddPolicy("p", "p", []string{"Carol", "data1", "read"})
It is recommended to remove AddPolicy, so as to avoid AddPolicy failure and affect the test

2022-06-26 13:52 UTC, hsluoyz commented
@JalinWang

2022-06-27 08:57 UTC, tangyang9464 approved these changes

2022-06-28 07:41 UTC, hsluoyz commented
@basimsahaf plz review

2022-08-24 02:46 UTC, hsluoyz commented
@JalinWang fix conflicts:

![image](https://user-images.githubusercontent.com/3787410/186308899-31ab4359-c5d8-45bb-802b-0a66e1dbc092.png)

2022-08-25 12:29 UTC, JalinWang commented
> @JalinWang fix conflicts:
> 
> ![image](https://user-images.githubusercontent.com/3787410/186308899-31ab4359-c5d8-45bb-802b-0a66e1dbc092.png)

@hsluoyz  Done

2022-08-25 15:30 UTC, hsluoyz commented
@JalinWang fix:

![image](https://user-images.githubusercontent.com/3787410/186707280-30680ef8-615f-406b-a363-c854c10ab208.png)

2022-08-26 04:54 UTC, tangyang9464 commented
@JalinWang Does this PR support custom v0-v5？

2022-08-26 07:25 UTC, JalinWang commented
> @JalinWang Does this PR support custom v0-v5？

@tangyang9464  Currently, no.

2022-08-26 07:35 UTC, JalinWang commented
> Reference in

Currently, no.

2022-08-26 08:03 UTC, JalinWang commented
> @JalinWang fix:
> 
> ![image](https://user-images.githubusercontent.com/3787410/186707280-30680ef8-615f-406b-a363-c854c10ab208.png)

@hsluoyz SORRRRY but now it's okay. Annoying conflict resolving 😣.

2022-08-26 14:24 UTC, hsluoyz commented
@JalinWang this PR makes code too complicated just to implement a not-so-important extra functionality, gorm-adapter is a benchmarking example and it should be kept simple. I suggest we putting this code into another adapter repo

2022-08-26 14:24 UTC, closed without merging