fix: lock method UpdatePolicies
casbin/gorm-adapter pull request #92
Opened 2021-03-26 14:24 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #81 

Sorry for the delay.

2021-03-26 14:29 UTC, closetool commented
@hsluoyz @saeedgeek @aryan828 plz review

2021-03-27 02:08 UTC, hsluoyz requested changes

2021-03-27 02:08 UTC, hsluoyz commented on go.sum
>  github.com/casbin/casbin/v2 v2.21.0 h1:M3A/R4quXcABNNj64P5LmYzREjoiviIcY6qbca/s+hs=
run `go mod tidy`

2021-03-27 02:08 UTC, hsluoyz commented on adapter.go
>  		} else {
What do you mean by `lock method UpdatePolicies`? Is it `add method UpdatePolicies`?

2021-03-27 03:23 UTC, hsluoyz approved these changes

2021-03-27 03:23 UTC, merged